#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(argparser)
  library(dplyr)
  library(data.table)
})

# Create a parser
p <- arg_parser("calculate the LD R2 for making the decay curve plot")

# Add command line arguments
p <- add_argument(p, "input", help="the ld.gz file for pairwise R2 generated by PCAone or plink")
p <- add_argument(p, "output", help="output file path, a tab-separated plain text file")
p <- add_argument(p, "--window", help="the window size in base pair used by PCAone or plink", default = 1000000L)
p <- add_argument(p, "--bins", help="the number of bins to split the R2 into", default = 100L)

# Parse the command line arguments
args <- parse_args(p)

## args <- commandArgs(trailingOnly = T)

fn <- args$input
fout <- args$output
window <- args$window
nbins <- args$bins


d <- fread(fn, sep = "\t", select= c("CHR_A", "BP_A", "BP_B", "R2"), data.table=F, nrows = 1000000000L)

## library(vroom)
## d <- vroom(fn, delim = "\t", show_col_types = FALSE, col_select = c(CHR_A, BP_A, BP_B, R2), altrep = c("chr", "int", "num"), n_max = 1000000000L)
## d <- vroom(fn, delim = "\t", show_col_types = FALSE, col_select = c(CHR_A, BP_A, BP_B, R2), n_max = 1000000000L)
message("done reading")

chrs <- unique(d$CHR_A)

res <- lapply(chrs, function(c){
  m <- d %>% filter(CHR_A==c) %>% transmute(Dist=BP_B - BP_A, R2) %>% arrange(Dist) %>%
    mutate(bin=ntile(Dist, nbins)) %>% group_by(bin) %>% summarise(num = n(),avg_R2 = mean(R2), std = sd(R2))
  m <- cbind(c, m)
  m
})

res <- do.call(rbind.data.frame, res)
res$bin <- res$bin * (window / nbins)
colnames(res) <- c("chr", "distance", "num", "avg_R2", "std")

write.table(res, fout, sep = "\t", col.names = F, row.names = F, quote = F)

